### ISSUE TITLE
Refactor "Create a project"

### ISSUE THREAD

**Issue by jana-scheidemann** [jana-scheidemann/DIY-App#18]

**Comment by jana-scheidemann** [comment]
## Value proposition
As a user with a new DIY project idea,
I want to create a new project within the app,
so that I can document and organize my project plans.

## Description

![Image](https://github.com/jana-scheidemann/DIY-App/assets/157710722/722a0140-2ca8-4ac8-9081-a17af3a59ccc)



## Acceptance criteria
- clicking "create a new project" opens a modal
- in the modal the user can enter all information for the new project into a form 
- saving the new project brings the user back to the overview page (Homepage)
- there the new project is listet on top so the user has a visual confirmation of the newly created project

## Tasks
- [ ] Create a feature branch feature/create-project-modal
- [ ] create a new modal "ModalAdd.js"
- [ ] style the modal according to the already existing modals
- [ ] import the ProjectFormNew in the modal with all necessary functions
- [ ] delete the page "/create"
