### ISSUE TITLE
Project Details Page

### ISSUE THREAD

**Issue by jana-scheidemann** [jana-scheidemann/DIY-App#2]

**Comment by jana-scheidemann** [comment]
## Value proposition
As a user interested in a specific DIY project, 
I want to access detailed information about the project, 
so that I can understand its requirements and the steps involved.

## Description


![Image](https://github.com/jana-scheidemann/DIY-App/assets/157710722/6835268a-b5a9-476f-bea9-3074e4d2fa47)


## Acceptance criteria
- [ ] users can access the details page of a project by selecting it from the project overview list
- [ ] the project details page displays all relevant information about the project in an organized and easily readable format
- [ ] users can navigate back to the project overview

## Tasks
- [ ] create a feature branch feature/project-details
- [ ] create a file [id].js
- [ ] add a Link to the title on the Homepage that refers to `/${[id]}`
- [ ] add key-value pair for image source
- [ ] component ProjectDetails: with all props
- [ ] add a button "back to all projects"
