### ISSUE TITLE
Template6

### ISSUE THREAD

**Issue by CharlineOe** [jana-scheidemann/DIY-App#26]

**Comment by CharlineOe** [comment]
## Value proposition
As a <user/role>
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team

**Comment by JessicaLoers** [comment]
Oops - I don't think this user story is quite finished yet. 

## Value Proposition
> in order to **_WHAT?_** 🤷‍♀️

Here is my suggestion ⬇️

**As a user** of the DIY App
**I want to** use my assistive technology with the app
**In order to** interact with the app independently and effectively, regardless of my physical abilities.

## Description
I somehow don't understand the description. 🫠

## Acceptance criteria
- [ ] All images must include descriptive alt text that accurately reflects the content and function of the image
- [ ] Ensure that all interactive elements (links, buttons, form elements) are properly labeled with accessible names
- [ ] Ensure that all parts of the app can be navigated using a keyboard alone

**Comment by jana-scheidemann** [comment]
Oh no. Sorry! We fixed it now.
