### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by CharlineOe** [jana-scheidemann/DIY-App#28]

**Comment by CharlineOe** [comment]
## Value proposition
As a <user/role>
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team

**Comment by JessicaLoers** [comment]
hey team - well done ✨

**Here're some thoughts to improve your Story.**

_The ACs could be a little more detailed and explicit, like...._ 

- [ ] A search field (indicated by a magnifying glass icon) is available on both the overview and favorites pages of the app.
- [ ] Users can enter keywords into the search field to initiate a search.
- [ ] Upon entering a keyword, a list of relevant projects or topics is displayed, matching the user's search query.
- [ ] Users have the option to clear their search results by clicking an "X" button, after which all projects or topics are displayed again, resetting the search functionality.

⚠️ **Please note the following:**
Depending on the complexity of the search functionality you wish to offer a Fuzzy Search could be beneficial. For example if you want your search feature to be tolerant of typos and slight variations in the search query, making the search experience more user-friendly and robust. One of the most popular libraries for implementing fuzzy search in JavaScript is [Fuse.js](https://www.fusejs.io/) 

**But it's absolutely fine to implement a simple search function as a first step that can be improved in a later user story. Our motto is: Make it work, make it efficient, make it nice.**
