### ISSUE TITLE
Create a Project

### ISSUE THREAD

**Issue by jana-scheidemann** [jana-scheidemann/DIY-App#3]

**Comment by jana-scheidemann** [comment]
## Value proposition
As a user with a new DIY project idea,
I want to create a new project within the app,
so that I can document and organize my project plans.

## Description
![Image](https://github.com/jana-scheidemann/DIY-App/assets/157710722/5d6bed2d-3874-40f6-a43f-2defdd957b4e)

## Acceptance criteria
- [ ] - users can access the form used to create projects
- [ ] users can input project details
- [ ] after completion, the newly created project is added to the
  user's Project list

## Tasks
- [ ] Create a feature branch feature/create-project
- [ ] Create component Navigation()
- [ ] Create links for HomePage, NewProject
- [ ] Create component ProjectFormNew()
- [ ] Prepare MongoDB to be usable in App 
- [ ] Create all required form fields based on database
      schema for user input
- [ ] Create Submit button to save newly created project in
     MongoDB
- [ ] Redirect user to HomePage() after creating the new
     project
