### ISSUE TITLE
Edit a Project

### ISSUE THREAD

**Issue by olivernowotny** [jana-scheidemann/DIY-App#4]
## Value Proposition

As a user managing my DIY projects, 
I want to be able to edit existing projects, 
so that I can make updates or changes as needed.

## Description

![Image](https://github.com/jana-scheidemann/DIY-App/assets/10808032/0c59c486-e6a1-4dfa-8749-acc729ddd314)

## Acceptance Criteria

- users can access the edit functionality for a project from 
the project details page 
- the edit interface presents all project details in editable 
fields, allowing users to make changes
- changes made to the project are saved automatically upon 
submission

## Tasks

- [ ] create a feature branch feature/edit-project
- [ ] add a "edit"-Button
- [ ] add a new form-handler-function to update the
      existing data of the project (update ProjectDetails
    component)
- [ ] create a Modal with a Form that lists all form fields 
    with the current content as the input
- [ ] add a submit- button to the Form that "saves all 
     changes", after submitting Modal closes
- [ ] add a "delete"-button to every step of the project,
      add a "add step"-button to create a new step
