### ISSUE TITLE
Delete a Project

### ISSUE THREAD

**Issue by olivernowotny** [jana-scheidemann/DIY-App#5]
## Value Proposition

As a user managing my DIY projects, 
I want to be able to delete projects that are no longer relevant, 
so that I can keep my project list up to date and organized.

## Description

![Image](https://github.com/jana-scheidemann/DIY-App/assets/10808032/538e1ba4-a85e-4831-985b-c14e2d3e46ab)

## Acceptance Criteria

- users can initiate the delete action for a project from the 
  project details page
- after confirmation, the selected project is removed from the 
  user's project list (User detail page ???)

## Tasks
- [ ] Create a feature branch feature/delete-project
- [ ] Add delete function to the detail page of a project
- [ ] Create a modal? / function to the deletion of the project
- [ ] Create confirm/cancel buttons on the modal
- [ ] If confirmed by the user, delete the object from the
      database
- [ ] If canceled, close the modal an do nothing
- [ ] After deletion, redirect the user to the HomePage()
- [ ] Check howto handle errors
