### ISSUE TITLE
Notifications/Toasts

### ISSUE THREAD

**Issue by jana-scheidemann** [jana-scheidemann/DIY-App#6]

**Comment by jana-scheidemann** [comment]
## Value proposition
As a user utilizing the different features of a DIY app, 
I want to receive toast messages/notifications upon completion of certain actions
so that I get confirmation about my actions.

## Description
![Image](https://github.com/jana-scheidemann/DIY-App/assets/157710722/ad190d8a-be86-425e-8949-6d9fe1694176)

## Acceptance criteria
- [ ] The App notifies the user via toast message about certain events
 such as the creation of a new project, or when a project has
 been edited/deleted 

## Tasks
- [ ] create a feature branch feature/notifications
- [ ] create a feedback modal for each user interaction 
    ("create", "update", ??)
