### ISSUE TITLE
Bookmark Projects Page

### ISSUE THREAD

**Issue by jana-scheidemann** [jana-scheidemann/DIY-App#7]
## Value proposition

- As a User interested in particular DIY projects,
- I want to be able to mark projects,
- So that I can access and track projects of interest

## Description

![Image](https://github.com/jana-scheidemann/DIY-App/assets/157911951/d267db84-c75c-477c-a840-5005416f313b)

## Acceptance criteria

- [ ] Users can mark projects as favorites on the details page, 
        overview page, favorite page
- [ ] Users can navigate to a favorite page that displays 
        their current favorites

## Tasks
- [ ] create a feature branch feature/bookmark-projects
- [ ] create favorites-Component
- [ ] add favorite-toggle-function to ProjectDetail() component      
- [ ] create navigation Item to favorites pages  
- [ ] create ../pages/favorites-structure
- [ ] adapt database schema, at favorites key
