### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by jana-scheidemann** [jana-scheidemann/DIY-App#8]
## Value proposition

- As a user accessing a large list of multiple DIY projects,
- I want to be able to organize and find projects easily by 
   filtering them based on different criteria, 
- So that I can be specific about which projects I want displayed.

## Description

![Image](https://github.com/jana-scheidemann/DIY-App/assets/157911951/807c4e9c-707f-47c6-8a1d-74ae1b9a55c8)

## Acceptance criteria

- [ ]    a menu provides options to sort projects by criteria such as 
          date created, difficulty level, or category, etc
- [ ]   users can filter projects based on attributes such as category, 
          materials required, or duration, etc

## Tasks

- [ ]  create a feature branch `feature/filter`
- [ ] Create a sort by button with an onClick handler that opens a modal (sort by)
- [ ] Create a filter by button with an onClick handler that opens a modal (filter by)
- [ ] Open the modal once the sort by button is clicked
- [ ] Sort the projects based on the applied user decision
- [ ] Open the modal once the filter by button is clicked
- [ ] Filter the projects based on the applied user decision
